import Head from 'next/head'
import Link from 'next/link';


export default function Header() {
  
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
  <header>
<ul>
<li>
        <Link href="/">
            <a>home</a>
        </Link>
    </li>
    <li>
        <Link href="/login">
            <a>Login</a>
        </Link>
    </li>
    <li>
        <Link href="/contact">
            <a>Contact</a>
        </Link>
    </li>
</ul>
  </header>
      </div>
    );
  }