import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Header from "../../components/header"
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
      </Header>
      <main>
      hello world {session?.user?.name}
      <section>
          <button onClick={() => signIn('github', { callbackUrl: 'http://localhost:3001/admin' })
  }
>
Sign In</button>
          <br />
          <button onClick={() => signOut()}>Sign Out</button>
        </section>
      </main>

      <footer>
       
      </footer>
    </div>
  )
}
