import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function Person({ name, species, gender }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{name}</h1>

        <div>
          <p>{species}</p>
          <p>{gender}</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤</p>
      </footer>
    </div>
  );
}

export async function getStaticPaths() {
  // Return a list of possible value for id

  const getCharacters = async () => {
    const data = await fetch("https://rickandmortyapi.com/api/character");
    const json = await data.json();
    return json.results;
  };

  const allCharacters = await getCharacters();

  const paths = allCharacters.map((person) => {
    return {
      params: {
        id: person.id.toString(),
      },
    };
  });

  // paths = [
  //   {
  //     params: {
  //       guid: "86a8a038-11df-4315-9d20-1d9f299a1007",
  //     },
  //   },
  //   {
  //     params: {
  //       guid: "86a8a038-11df-4315-9d20-123123312",
  //     },
  //   },
  // ];

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  // Fetch necessary data for the blog post using params.id
  // const foundPerson = peopleJson.find((person) => person.guid === params.guid);

  // We need to fetch the data for one spefici character here
  const fetchCharacter = async () => {
    const data = await fetch(
      `https://rickandmortyapi.com/api/character/${params.id}`
    );
    const json = await data.json();
    return json;
  };
  const foundPerson = await fetchCharacter();

  return {
    props: foundPerson,
  };
}