import Head from "next/head";

import styles from "../../styles/Home.module.css";
import peopleJson from "../../libs/people-data";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>People</h1>

        <div>
          <ul>
            {peopleJson.map((person) => (
              <li key={person.guid}>{person.name}</li>
            ))}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤</p>
      </footer>
    </div>
  );
}