import Head from "next/head";

import styles from "../../styles/Home.module.css";
import peopleJson from "../../libs/people-data";

export default function Home() {
  const router = useRouter();
  const [characters, setCharacters] = useState([]);

  const handleOnClick = (id) => {
    router.push(`/courses/${id}`);
  };

  useEffect(() => {
    const getCharacters = async () => {
      const data = await fetch("https://rickandmortyapi.com/api/character");
      const json = await data.json();
      setCharacters(json.results);
    };

    getCharacters();
  }, []);

  console.log("characters", characters);
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>People</h1>

        <div>
          {/* <ul>
            {peopleJson.map((person) => (
              <li key={person.guid}>{person.name}</li>
            ))}
          </ul> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Made with ❤</p>
      </footer>
    </div>
  );
}